
[profile.release]

lto = true

[profile.fastdev]

inherits = "dev"
opt-level = 0
debug = false

[workspace]

resolver = "2"

members = [
  "app_core_template",
  # TODO
  # "{{project-name}}",
  "webapp_core",
  "webapp_yaml_config",
  # TODO
  "test_plugin",
]
