[template]

cargo_generate_version = ">=0.10.0"

ignore = [
  "target",
]

exclude = [
  ".cargo-generate",
]

[placeholders]

license = { type = "string", prompt = "What license to use?", choices = ["APACHE", "MIT"], default = "MIT" }
