[template]

cargo_generate_version = ">=0.10.0"

ignore = [
  "README.md",
  ".cargo-generate",
]

[hooks]

post = [
  ".cargo-generate/post-hook.rhai",
]

[placeholders]

license = { type = "string", prompt = "What license to use?", choices = ["APACHE", "MIT"], default = "MIT" }
