use serde::{Deserialize, Serialize};
use structdoc::StructDoc;

#[derive(Serialize, Deserialize, StructDoc, Clone)]
pub struct OpenAPI {
    /// URI which should respond with autogenerated OpenAPI specification
    pub spec_uri: String,
    /// URI which should respond with Swagger interface to OpenAPI specification
    pub swagger_uri: Option<String>,
}

#[derive(Serialize, Deserialize, StructDoc, Clone)]
pub struct Config {
    /// Bind web application to specified address. For example, "127.0.0.1"
    pub bind_address: String,
    /// Bind web application to specified port. For example, 8080
    pub bind_port: u16,
    /// Logging configuration
    pub loggers: crate::logging::Loggers,
    /// Enable OpenAPI/Swagger documentation for HTTP API
    pub openapi: Option<OpenAPI>,
}
